# Lista de IPs de todas las máquinas en la red (separadas por coma)
# El orden en esta lista define el ID del Nodo.
# Posición 1 = Nodo 1, Posición 2 = Nodo 2, etc.
server.port=8085
hospital.nodes.ips=192.168.1.10,192.168.1.11,192.168.1.12,192.168.1.13,192.168.1.14
